spring:
  application:
    name: registro-contatos-clean-arch

  datasource:
    url: jdbc:h2:mem:contato_db
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080
